# Use the official Maven image with Java 17 as a parent image
FROM maven:3.8.4-openjdk-17-slim AS build

# # Set the working directory in the container
WORKDIR /app

# Copy the Maven project descriptor files
COPY pom.xml .
COPY src ./src

# Build the application
RUN mvn clean package

# Use a smaller base image for the runtime environment
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the built JAR file from the build stage
COPY --from=build /app/target/*.jar ./app.jar

# Expose the port on which the application will run
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "app.jar"]
